// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/dna_scripts_version.test.ts.

/** The version of the `@ggdna/dna-scripts` package. */
export const dnaScriptsVersion = '0.2.1';
